Repository mikeharrison57/curious-reader, pull requests merged in 2022-08, with the labels that each got.

#16 Refactor/codebase
  src/BookCard/BookCard.css
  src/BookCard/BookCard.tsx
  src/BookGenrePage/BookGenrePage.tsx
  src/ErrorMessage/ErrorMessage.css
  src/ErrorMessage/ErrorMessage.tsx
  src/Sidebar/Sidebar.css
  src/Sidebar/Sidebar.tsx
  src/TopBooks/TopBooks.tsx
  src/app/App.css
  src/assets/orange-loading.gif
  src/index.css
Labels: enhancement

#17 Docs/readme draft
  README.md
Labels: documentation

#19 Refactor/state management restructure
  src/BookGenrePage/BookGenrePage.tsx
  src/Interfaces.tsx
  src/api-calls.tsx
  src/app/App.tsx
Labels: enhancement

#20 Testing/finish testing
  cypress/e2e/genre-page-spec.cy.ts
  cypress/e2e/main-page-spec.cy.ts
  src/Sidebar/Sidebar.tsx
Labels: Testing
